sudo: required
language: go

go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - make test

after_success:
  - if [ -z "$QUAY_USER" ]; then
      echo "PR build, skipping Quay push";
    else
      echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io;
      make quay-push;
    fi

